### ISSUE TITLE
The main language is always English, despite the change to another language

### ISSUE THREAD

**Issue by dawnog** [globaleaks/whistleblowing-software#4198] opened 2024-09-25 12:33 UTC
### What version of GlobaLeaks are you using?

5.0.10

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

The main language is always English, despite the change to another language. Globaleaks ver. 5.0.10  is installed on a VPS running Debian 11
Although the only language set is Polish, in the application on html lang="en’
This causes the Chrome browser, to want to translate the page which is confusing for users and additionally the translation is wrong
How can this be changed?
Please help

**Comment by evilaliv3** [comment] 2024-09-25 12:41
Thank you, would you please reproduce the error in try globaleaks.org and give us the url or screenshots to see the problem?

**Comment by dawnog** [comment] 2024-09-25 13:38
Thank you for help, sure , here is link : https://dlasygnalisty.pl/#/

śr., 25 wrz 2024 o 14:42 Giovanni Pellerano ***@***.***>
napisał(a):

**Comment by evilaliv3** [comment] 2024-09-25 19:49
Thank you.

I don't see this happening on my chrome instance , where the page appears correctly in polish.

Would you please retry with a fresh new setup of chrome? I suspect you may have enabled automatic translations or something

**Comment by dawnog** [comment] 2024-10-01 13:53
The problem occurs on various devices but only on Chrome.
The problem is that the browser offers and translates Polish to Polish and additionally makes errors.

The browser offers a translation because there is html lang=“en” in the code, even though Polish is set as the main and only language.

**Comment by evilaliv3** [comment] 2024-10-05 10:41
This should be already fixed in 5.0.11.

If you have still not updated you could wait for 5.0.12 that will be available shortly including some other minor corrections to issues reported by other community members.

**Closed by evilaliv3** 2024-10-05 10:41 UTC
Labels: T: Bug, Triage

**Comment by dawnog** [comment] 2024-10-08 06:38
unfortunately it did not help....still the same thing

**Comment by evilaliv3** [comment] 2024-10-08 10:48
@dawnog : did you encounter this issue on release 4 ?

**Comment by dawnog** [comment] 2024-10-08 11:50
If I remember correctly, this problem also occurred on rel. 4

**Comment by dawnog** [comment] 2024-10-08 12:32
Great! Thank you

wt., 8 paź 2024, 14:03 użytkownik Giovanni Pellerano <
***@***.***> napisał:

**Comment by evilaliv3** [comment] 2024-10-08 14:18
@dawnog : https://try.globaleaks.org/#/signup?lang=pl

What do you think about current status here?

I've anticipated a patch that we are going to include in 5.0.13. This should fix the problem.

**Comment by dawnog** [comment] 2024-10-08 14:54
That looks nice! Great!

wt., 8 paź 2024, 16:19 użytkownik Giovanni Pellerano <
***@***.***> napisał:

**Comment by evilaliv3** [comment] 2024-10-08 14:58
Super!

Expect to be able to update to 5.0.13 in around 20 minutes then :)

Thank you for your feedback.

**Comment by dawnog** [comment] 2024-10-10 08:03
Good morning!

 

This is strange, I checked again, even though I see in the code setting lang=pl, chrome still offers the translation. Now I don't understand anymore.

 

please help and regards

Dawid

**Comment by evilaliv3** [comment] 2024-10-10 10:17
@dawnog  would you please try with this? https://languagetest.try.globaleaks.org/#/

I tried to disable the "Content-language" http header, because actually i think we do not really need it.

Maybe having an hardcoded value changed dynamically confuses chrome.

**Comment by evilaliv3** [comment] 2024-10-10 15:32
@dawnog ?

**Comment by dawnog** [comment] 2024-10-11 07:51
Good morning!

 

Thank you for your email, sorry for the delay in communication. I was on the road all day yesterday.

 

I checked, unfortunately Chrome still wants to translate .... 

 

Have a good day

Dawid

**Comment by dawnog** [comment] 2024-10-17 10:16
hello!

 

I found a strange discrepancy that may be the cause of the automatic translation problems.

 

When you do a page code preview via devtools the variable lang=en.

But if you preview the source of the page then the variable lag=en.

 

 

 

This can be confusing for chrome.

please help

dawid

**Comment by evilaliv3** [comment] 2024-10-20 07:16
@dawnog in your previous message, probably by mistake you are saying that in BOTH the conditions you see 'en'. Maybe you wanted to say that in one of the conditions the language is set as pl?

The software within the source code need to state that the language is 'en' as a fallback but then it is correctly setting the language to the language selected by the user.

If you find a way of fixing this please feel free to propose a pull request amending the code.

Thank you

**Comment by evilaliv3** [comment] 2024-10-20 08:32
@dawnog: if you would like please feel free to pass me a link to your site and i may give it a look.

**Comment by dawnog** [comment] 2024-10-21 09:48
Sure, https://dlasygnalisty.pl/#/

**Comment by evilaliv3** [comment] 2024-10-21 15:06
Thank you @dawnog , at the moment unfortunately i'm not able to identify any issue.

**Comment by dawnog** [comment] 2024-10-22 08:56
Thank you Giovanni for the information, I hope that in some time we will somehow solve this problem 😊 Greetings

**Comment by dawnog** [comment] 2024-10-22 16:08
How about a solution that the GlobaLeaks application takes the page
template either from its own sources or from the location specified in the
server configuration, e.g. if the application is installed on Linux in
/var/globaleaks/ then let the application first try to find the html in
/var/globaleaks/html_templates, and if it does not find it there, then it
will take its default one and load it. This solution gives us the advantage
that we can already type <html lang="pl"> there.

wt., 22 paź 2024, 10:55 użytkownik Dawid Nogaj ***@***.***>
napisał:

**Comment by dawnog** [comment] 2024-12-05 11:31
I have this idea for a solution to the auto-translation problem, or rather a workaround.

You can test add a meta tag to the <head> section of the page:
<meta name=‘google’ content=‘notranslate’>.
If it works, maybe add a switch in the settings whether the page should be translated by google or not.

What do you think?

**Comment by evilaliv3** [comment] 2024-12-05 13:38
Thank you @dawnog 

Actually we would prefer to avoid using browser specific settings (e.g. the suggestion relate only to chrome)

I've found that we could use translate="no" on the <html> tag that is the standard way to achieve same result. 

I've applied this configuration on https://languagetest.try.globaleaks.org/#/

Would you please test if it works for you?

**Comment by dawnog** [comment] 2024-12-05 13:55
thank you for the quick response! 
Chrome still offers translation, but I don't know if it translates.
Please put a standard questionnaire on this link please, then I will be able to finally check .

**Comment by evilaliv3** [comment] 2024-12-05 18:35
@dawnog : what do you mean with standard questionnaire? this link loads the globaleaks default questionnaire.

**Comment by dawnog** [comment] 2024-12-06 08:02
Hi! I checked more carefully, unfortunately chrome still offers to translate the page. 
One good thing is it does not do this translation automatically.
