### ISSUE TITLE
On version 5.0.12 initial User password creation fails on systems running with no escrow keys 

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/whistleblowing-software#4228] opened 2024-10-08 12:28 UTC
### What version of GlobaLeaks are you using?

5.0.12

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

We have just updated to 5.012 an have discovered a major bug. When a new user is trying to create the first password, th cration fails. This has been tested on 2 different servers - same result. Issue quite urgent, as our production system is affected.

![image](https://github.com/user-attachments/assets/84ea1d63-b345-4cb3-8f37-662fc76bc682)

Last entries in globaleaks.log:

2024-10-08 12:12:50+0000 [-] [E] nacl.exceptions.TypeError None\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/user/operation.py", line 61, in change_password\n    user.crypto_bkp_key, user.crypto_rec_key = GCE.generate_recovery_key(cc)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 265, in generate_recovery_key\n    pub_key = PrivateKey(prv_key, Base64Encoder).public_key.encode(Base64Encoder)\n\n  File "/usr/lib/python3/dist-packages/nacl/public.py", line 90, in __init__\n    "bytes long raw secret key").format(self.SIZE)\n\nnacl.exceptions.TypeError: PrivateKey must be created from a 32 bytes long raw secret key\n
2024-10-08 12:13:02+0000 [-] [E] Unhandled exception raised:
2024-10-08 12:13:02+0000 [-] [E] nacl.exceptions.TypeError None\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/user/operation.py", line 61, in change_password\n    user.crypto_bkp_key, user.crypto_rec_key = GCE.generate_recovery_key(cc)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 265, in generate_recovery_key\n    pub_key = PrivateKey(prv_key, Base64Encoder).public_key.encode(Base64Encoder)\n\n  File "/usr/lib/python3/dist-packages/nacl/public.py", line 90, in __init__\n    "bytes long raw secret key").format(self.SIZE)\n\nnacl.exceptions.TypeError: PrivateKey must be created from a 32 bytes long raw secret key\n
2024-10-08 12:13:10+0000 [-] [D] [1] Sending email to yyy using SMTP server [mail.globaleaks.org:587] [TLS]
2024-10-08 12:13:10+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb3a5361da0>
2024-10-08 12:13:11+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb3a5361da0>
2024-10-08 12:13:12+0000 [-] [D] [1] Sending email to xxx using SMTP server [mail.globaleaks.org:587] [TLS]
2024-10-08 12:13:12+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb38f61b4e0>
2024-10-08 12:13:12+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb38f61b4e0>
2024-10-08 12:13:13+0000 [-] [E] Unhandled exception raised:
2024-10-08 12:13:13+0000 [-] [E] nacl.exceptions.TypeError None\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/user/operation.py", line 61, in change_password\n    user.crypto_bkp_key, user.crypto_rec_key = GCE.generate_recovery_key(cc)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 265, in generate_recovery_key\n    pub_key = PrivateKey(prv_key, Base64Encoder).public_key.encode(Base64Encoder)\n\n  File "/usr/lib/python3/dist-packages/nacl/public.py", line 90, in __init__\n    "bytes long raw secret key").format(self.SIZE)\n\nnacl.exceptions.TypeError: PrivateKey must be created from a 32 bytes long raw secret key\n

**Comment by evilaliv3** [comment] 2024-10-08 13:43
Thank you @schris-dk 

This is actually caused by a regression that i introduced by mistake while working on the other issue that you reported: https://github.com/globaleaks/whistleblowing-software/issues/4211

This bug applies only in systems running with no exscrow keys and is very specific to 5.0.12

**Comment by evilaliv3** [comment] 2024-10-08 13:47
Fixed and the patch will be included by today on release 5.0.13

**Closed by evilaliv3** 2024-10-08 13:47 UTC
Labels: T: Bug, C: Backend
