### ISSUE TITLE
Datepicker not opening

### ISSUE THREAD

**Issue by pcinacio** [globaleaks/whistleblowing-software#4209] opened 2024-10-02 08:34 UTC
### What version of GlobaLeaks are you using?

5.0.11
![Screenshot_1](https://github.com/user-attachments/assets/106c215d-2417-466b-8c11-d61db9a7849b)
![Screenshot_2](https://github.com/user-attachments/assets/778fb944-ccca-4441-bd80-cf0a765582ad)

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

When I open a report to fill in Portuguese, the date picker is not appearing anymore for the question 'When did the events happen?'. In English, I'm not noticing any issues. The date picker opens. Am I missing something? This was working in the past.
Thanks in advance.

**Comment by evilaliv3** [comment] 2024-10-02 10:27
Thank you for reporting this @pcinacio 

Actually version 5 is a full rewrite of the client application. 

We are receiving feedback from our users like like on some minor defects and with strong priority we are proceeding that all is working correctly. I will come back to you if we need to collect some information to reproduce the issue.

**Comment by evilaliv3** [comment] 2024-10-05 13:45
Issue identified.

It is related to locale; i just produced a patch that fixes loading of locale for Porttugues and other languages.

**Comment by evilaliv3** [comment] 2024-10-05 13:49
Closing the ticket for now since a patch that includes a fix for Portuguese has been made and it will be included in minor release 5.0.12

I took care of rechecking every language but i do not exclude some defects may still exist on some languages.

**Closed by evilaliv3** 2024-10-05 13:49 UTC
Labels: T: Bug, C: Client
