### ISSUE TITLE
Missing all text after Globaleaks 5.0.7 upgrade (from version 5.0.6)

### ISSUE THREAD

**Issue by marcopvl** [globaleaks/whistleblowing-software#4191] opened 2024-09-16 13:23 UTC
### What version of GlobaLeaks are you using?

5.0.7

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

All the text are missing, see the attached file.

Thanks

[bug_5.0.7.pdf](https://github.com/user-attachments/files/17013819/bug_5.0.7.pdf)

**Comment by evilaliv3** [comment] 2024-09-16 14:21
@marcopvl : can you reach me on community.gobaleaks.org so that we could look at your setupdì together?

**Comment by diegolagoglez** [comment] 2024-09-17 12:31
Hello,

I think this is a duplicate of [4190](https://github.com/globaleaks/whistleblowing-software/issues/4190).

Regards.

**Comment by evilaliv3** [comment] 2024-09-18 16:20
Yes i think so, let me close this ticket in favour of the previous.

**Closed by evilaliv3** 2024-09-18 16:20 UTC
Labels: T: Bug, Triage
