### ISSUE TITLE
Incorrect export of questionnaires leads to export only one language

### ISSUE THREAD

**Issue by diegolagoglez** [globaleaks/whistleblowing-software#4190] opened 2024-09-16 12:02 UTC
### What version of GlobaLeaks are you using?

5.0.7

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows, Android, Linux

### Describe the issue

Just after upgrade on Ubuntu 22.04 using `apt` (from version 5.0.6 to 5.0.7, and only that package; no more packages were upgraded), all the text in the main page and subpages of the Globaleaks application are missing. Buttons with text are shown, some buttons work, but all the text is missing.

I've tested it in Windows, Linux and Android, with both Chrome and Firefox.

I have custom CSS but I've checked it disabling my custom CSS and the problem persist.

Javascript console raises this error:

`Content-Security-Policy: La configuración de la página bloqueó la aplicación de un estilo en línea (style-src-elem) porque viola la siguiente directiva: “style-src 'self' 'sha256-pru43GdcNLwb4MwzOriCI9/9cKBzE5xeoLWHlKai1As='” [platform-browser.mjs:356:17](webpack:///node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs)`

Automatic translation is: `Content-Security-Policy: The page configuration blocked the application of an inline style (style-src-elem) because it violates the following directive: “style-src 'self' 'sha256-pru43GdcNLwb4MwzOriCI9/9cKBzE5xeoLWHlKai1As='” platform-browser.mjs:356:17`

I attach some (limited) screenshots to show the problem:

![globaleaks-missing-text-1](https://github.com/user-attachments/assets/bf9fc4e8-01f2-4508-ba4c-103967c147a1)
![globaleaks-missing-text-2](https://github.com/user-attachments/assets/23c846ae-2f14-48ee-bcaf-599341ffaf92)
![globaleaks-missing-text-3](https://github.com/user-attachments/assets/f68061c3-5f22-466e-8740-861ec42adaaa)

**Comment by evilaliv3** [comment] 2024-09-16 12:24
Thank you @diegolagoglez  for reporting this.

Are you able to proide me a lin to your platform or on community.globaleaks.org?

Thanm yuu

**Comment by diegolagoglez** [comment] 2024-09-17 07:32
Sorry, @evilaliv3, a this moment my platform is still confidential :(

**Comment by JaviAlama** [comment] 2024-09-18 07:24
Hello, the same thing happened to us in our test environment after upgrading to version 5.0.7.

**Comment by evilaliv3** [comment] 2024-09-18 08:58
Thank you @JaviAlama , do you have a link to your platform that i could test?

**Comment by evilaliv3** [comment] 2024-09-18 16:22
@JaviAlama @diegolgz  @marcopvl: I think i've found the reason of the failure.

The problem is not in the update to 5.0.7, but in the function that export the questionnaires on version 5.

Do you confirm that you have updated to version 5, tried to export your questionnaires and then reimport them?

I noticed that the export function is currently exporting only one language.

**Comment by diegolagoglez** [comment] 2024-09-19 08:20
With version 5.0.8 the error persist, and I haven't been able to remove a questionnaire after an export (export worked well) due to the same error:

```
Content-Security-Policy: La configuración de la página bloqueó la aplicación de un estilo en línea (style-src-attr) porque viola la siguiente directiva: “style-src 'self' 'sha256-pru43GdcNLwb4MwzOriCI9/9cKBzE5xeoLWHlKai1As='” platform-browser.mjs:593:15
Content-Security-Policy: La configuración de la página bloqueó la aplicación de un estilo en línea (style-src-attr) porque viola la siguiente directiva: “style-src 'self' 'sha256-pru43GdcNLwb4MwzOriCI9/9cKBzE5xeoLWHlKai1As='” ng-bootstrap.mjs:7441:20
Content-Security-Policy: La configuración de la página bloqueó la aplicación de un estilo en línea (style-src-elem) porque viola la siguiente directiva: “style-src 'self' 'sha256-pru43GdcNLwb4MwzOriCI9/9cKBzE5xeoLWHlKai1As='” platform-browser.mjs:356:17
XHRDELETE
https://globaleaks.example.org/api/admin/questionnaires/c541f5c2-24ed-4081-9298-98397d8ba8f3
[HTTP/2 500  16ms]

ERROR 
Object { headers: {…}, status: 500, statusText: "OK", url: "https://globaleaks.example.org/api/admin/questionnaires/c541f5c2-24ed-4081-9298-98397d8ba8f3", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://globaleaks.example.org/api/admin/questionnaires/c541f5c2-24ed-4081-9298-98397d8ba8f3: 500 OK", error: {…} }
error: Object { error_message: "InternalServerError [Unexpected]", error_code: 1, arguments: (1) […] }
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit()
}
message: "Http failure response for https://globaleaks.example.org/api/admin/questionnaires/c541f5c2-24ed-4081-9298-98397d8ba8f3: 500 OK"
name: "HttpErrorResponse"
ok: false
status: 500
statusText: "OK"
url: "https://globaleaks.example.org/api/admin/questionnaires/c541f5c2-24ed-4081-9298-98397d8ba8f3"
<prototype>: Object { … }
```

**Comment by evilaliv3** [comment] 2024-09-19 09:15
Thank you @diegolagolgz

Actually the  errors on the content security policy are unrelated.

Are you able to create a platform on try.globaleaks.org where to reproduce the error? this would be really helpful.
Thank you

**Comment by diegolagoglez** [comment] 2024-09-20 09:51
I've just installed version 5.0.9 and it partially fixes the problem.

Almost all text is shown but the questionnaires' buttons' text are not shown and, when clicked, they also don't work (they don't go to the next tab).

This image is an example of the main form button that should show "Siguiente" (Next).

![imagen](https://github.com/user-attachments/assets/e4c62148-3e4b-4da0-96ce-207d9af526a1)

**Comment by JaviAlama** [comment] 2024-09-20 09:57
It's true! Same behaviour on our test project after updating from 5.0.3 to 5.0.9.

**Comment by evilaliv3** [comment] 2024-09-21 18:23
Thank you, it should be all fixed now in 5.0.10

**Comment by JaviAlama** [comment] 2024-09-23 06:22
Good morning. After upgrading to 5.0.10, submit button and other texts and functionalities seem to be fixed.

**Comment by evilaliv3** [comment] 2024-09-23 09:50
Thank you @JaviAlama . I'm closing the ticket then, please feel free to reopen it if you notice any defect.

**Closed by evilaliv3** 2024-09-23 09:50 UTC
Labels: T: Bug, C: Client

**Comment by diegolagoglez** [comment] 2024-09-23 11:37
Little late but I can confirm that version 5.0.10 fixes the error.

Thanks very much.

**Comment by evilaliv3** [comment] 2024-11-07 09:39
@JaviAlama @diegolagoglez : i think the error is happening again.

We will be rechecking this with high priority.

The issue is tracked by: https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/4298
